### PR TITLE
Add various trackers, Cloudflare Bypass, Add 2FA support

### LINKED ISSUE #4: Cloudflare cannot be passed
HUNO and maybe more are broken due to cloudflare. 

Seems like a fix is in the works for [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1420#discussioncomment-8447949) so we should switch to that when it does work.

### PR DESCRIPTION
**Pull request by SavageCore**
1. Pin package versions and make it run.
2. Save screenshots to screenshots folder and ignore them in git
3. BLU, HUNO, OPS, RED and MTV 2FA Support
4. Bypass HUNO cloudflare
5. Add BTN
6. Add GGN
7. Add PTP
8. Make browser configurable with `config.ini` - seleniumbase makes this easy!
9. Actual full-page screenshots not just the maximum height of your monitor
10. Uses [implicitly_wait](https://www.selenium.dev/documentation/webdriver/waits/) to wait until elements are available, much faster than the arbitrary sleeps
11. Hide passkey elements on CRT and MTV (there may be more on sites I don't have access to)
12. Add OTW

Fixes #4 by switching to seleniumbase and using the [UC mode](https://seleniumbase.io/help_docs/uc_mode/#uc-mode). You'll notice HUNO is happy with the default implementation whereas BTN required some more work

### CODE REVIEW

**Comment by SavageCore** [comment]
Once this is merged I have refactored the code so we have tracker classes, inheriting from a base class. There was a lot of code duplication.

https://github.com/SavageCore/TrackerScreenshot/tree/feature/refactor

I can also merge and push along with this PR, let me know.

**Comment by SavageCore** [comment]
> Do you think this will work with the Brave browser as well?

Updated! 

If using Brave or Opera you must specify `binary_location` in the `config.ini` file.

More info: https://stackoverflow.com/a/77573763/1190476

**Comment by KlevGG** [comment]
Hello, thank you for your huge contribution. I am traveling and didn't get the chance to review/test. I will check it in 2-3 weeks!

**Comment by SavageCore** [comment]
> Hello, thank you for your huge contribution. I am traveling and didn't get the chance to review/test. I will check it in 2-3 weeks!

That's all good, take your time, enjoy your travels!

**Review by KlevGG — APPROVED** [review]

**Pull request merged**
